# Generated by Django 4.2.25 on 2025-10-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveIntegerField(default=0, editable=False)),
                ('path', models.CharField(db_index=True, editable=False, max_length=1024)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'ordering': ['parent_id', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategorySimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_left', to='categories.category')),
                ('cat_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_right', to='categories.category')),
            ],
            options={
                'indexes': [models.Index(fields=['cat_left'], name='categories__cat_lef_8eb135_idx'), models.Index(fields=['cat_right'], name='categories__cat_rig_a9f35f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='categorysimilarity',
            constraint=models.UniqueConstraint(fields=('cat_left', 'cat_right'), name='unique_similarity_pair'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='categories__parent__91c7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['depth'], name='categories__depth_448965_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='categories__path_d816b7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='categories__name_e3ad98_idx'),
        ),
    ]
